default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 100
  timeout: 5000

development:
  <<: *default
  database: sustainable-seafood-development

test:
  <<: *default
  database: sustainable-seafood-test

production:
  <<: *default
  database:
