# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d38e47be1d31431b3bed4960b6ffb3476afd8b85f3eae3dcd93eee85c66951d3ebfd76da89cb3d35c5e393e134f6c1a0f9e1f35fbb6118af4f0d36d37e66a3

test:
  secret_key_base: 86236b49702024a3d0d1fe6679af4424ba90f1dcc76dccfc38ac7c4569093d65054912ebb293dfee68a834bd0410690f812f97c5a182088dcfd49376e35c988e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
